// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtycgujavlhffqoulchc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0eWNndWphdmxoZmZxb3VsY2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTAzNjksImV4cCI6MjA2MDEyNjM2OX0.19WgmPL8191_lEhU043noD0vkZ-4w_GVatDJzBqZWNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);